### ISSUE TITLE
请楼主帮忙看看--打开工程编译过程中碰到这些问题。

### ISSUE THREAD

**Issue by shentu521** [TaoistKing/Video-Jitter-Buffer#2]
Undefined symbols for architecture arm64:
  "rtc::ThreadCheckerImpl::~ThreadCheckerImpl()", referenced from:
      rtc::ThreadChecker::~ThreadChecker() in libVideoReceiver.a(thread_posix.o)
  "rtc::ThreadCheckerImpl::ThreadCheckerImpl()", referenced from:
      rtc::ThreadChecker::ThreadChecker() in libVideoReceiver.a(thread_posix.o)
  "rtc::ThreadCheckerImpl::CalledOnValidThread() const", referenced from:
      webrtc::ThreadPosix::~ThreadPosix() in libVideoReceiver.a(thread_posix.o)
      webrtc::ThreadPosix::Start() in libVideoReceiver.a(thread_posix.o)
      webrtc::ThreadPosix::Stop() in libVideoReceiver.a(thread_posix.o)
      webrtc::ThreadPosix::SetPriority(webrtc::ThreadPriority) in libVideoReceiver.a(thread_posix.o)
ld: symbol(s) not found for architecture arm64

**Comment by shentu521** [comment]
已解决：
1.base目录下有三个文件没有添加进工程。
2.要在xcode-buildSettings中添加宏定义 ：Preproessor Macros ---  WEBRTC_POSIX

**Comment by TaoistKing** [comment]
之前的工程里少加了几个ThreadChecker的文件，现在加进去了，更新下就好了。
